#!/usr/bin/env python3
"""Build paper/tables/tab_baseline.tex from progress-oriented eval files."""

from __future__ import annotations

import json
import sys
from pathlib import Path

RAFT_DATA = Path("paper/data/eval_metrics_raft.anon.jsonl")
COMMAND_PARTITION_DATA = Path("paper/data/eval_command_local_partition.anon.jsonl")
OUT = Path("paper/tables/tab_baseline.tex")
OUT.parent.mkdir(exist_ok=True)


def load(path: Path) -> list[dict]:
    if not path.exists():
        sys.exit(f"missing {path}")
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle]


def command_partition_summary() -> dict:
    records = load(COMMAND_PARTITION_DATA)
    for record in records:
        if record.get("metric_name") == "summary":
            return record["scenario_params"]
    sys.exit(f"missing summary record in {COMMAND_PARTITION_DATA}")


def main() -> None:
    raft = load(RAFT_DATA)
    partition = command_partition_summary()
    quorum_results = [
        record["scenario_params"].get("write_succeeded")
        for record in raft
        if record["scenario"] == "baseline_raft_quorum_lost"
    ]
    if not quorum_results:
        sys.exit("missing baseline_raft_quorum_lost records")

    raft_succeeded = sum(1 for result in quorum_results if result)
    seqs = partition["sequence_numbers"]
    rows = [
        "Quorum loss & Raft cluster & 2 of 3 voters isolated & "
        f"{raft_succeeded}/{len(quorum_results)} writes succeeded & "
        r"quorum-dependent progress \\",
        r"\addlinespace",
        "Direct command accept path & Rescue OIS command \\texttt{syncd} accept path & "
        "command/storage available; responder \\texttt{syncd} isolated & "
        f"{partition['successful_commits']}/{partition['attempted_writes']} command journal commits; "
        f"seq. {min(seqs)}--{max(seqs)}; "
        f"{partition['duplicate_sequence_count']} duplicate seqs. & "
        r"no responder-quorum dependency on this implemented path \\",
    ]

    with OUT.open("w", encoding="utf-8") as handle:
        handle.write("% Auto-generated by paper/scripts/generate_baseline_table.py.\n")
        handle.write("% Do not edit; re-run the script after eval data changes.\n")
        for row in rows:
            handle.write(row + "\n")
        handle.write(r"\bottomrule" + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
