#!/usr/bin/env python3
"""Generate paper/tables/tab_evaluation.tex from eval_metrics.jsonl."""

from __future__ import annotations

import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

DATA = Path("paper/data/eval_metrics.jsonl")
OUT = Path("paper/tables/tab_evaluation.tex")
OUT.parent.mkdir(exist_ok=True)


def load_records():
    if not DATA.exists():
        sys.exit(f"ERROR: {DATA} missing")
    with DATA.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle]


def percentile(xs, p):
    xs_sorted = sorted(xs)
    k = (len(xs_sorted) - 1) * (p / 100)
    f = int(k)
    c = min(f + 1, len(xs_sorted) - 1)
    if f == c:
        return xs_sorted[f]
    return xs_sorted[f] + (xs_sorted[c] - xs_sorted[f]) * (k - f)


def main():
    records = load_records()

    boot = defaultdict(list)
    for record in records:
        if record["scenario"] == "bootstrap_latency" and record.get("value_ms") is not None:
            boot[record["scenario_params"]["aoi_polygons"]].append(record["value_ms"])

    prop = defaultdict(list)
    for record in records:
        if record["scenario"] == "field_edit_propagation" and record.get("value_ms") is not None:
            prop[record["scenario_params"]["queue_depth"]].append(record["value_ms"])

    rec = defaultdict(list)
    for record in records:
        if record["scenario"] == "wan_recovery" and record.get("value_ms") is not None:
            rec[record["scenario_params"]["partition_s"]].append(record["value_ms"])

    tput = []
    for record in records:
        if record["scenario"] == "command_throughput":
            if record["run_index"] == 0:
                continue
            tput.append(record["scenario_params"]["events_per_sec"])

    rows = []
    rows.append(r"\textit{Bootstrap latency vs.\ AOI complexity} & & & \\")
    for key in sorted(boot.keys()):
        values = boot[key]
        rows.append(
            f"  \\hspace{{2mm}}AOI polygons = {key} & {len(values)} & "
            f"{statistics.median(values):.2f} & {percentile(values, 95):.2f} \\\\"
        )
    rows.append(r"\addlinespace")
    rows.append(r"\textit{Field-edit propagation vs.\ queue depth} & & & \\")
    for key in sorted(prop.keys()):
        values = prop[key]
        rows.append(
            f"  \\hspace{{2mm}}queue depth = {key} & {len(values)} & "
            f"{statistics.median(values):.1f} & {percentile(values, 95):.1f} \\\\"
        )
    rows.append(r"\addlinespace")
    rows.append(r"\textit{WAN recovery vs.\ partition duration} & & & \\")
    for key in sorted(rec.keys()):
        values = rec[key]
        rows.append(
            f"  \\hspace{{2mm}}partition = {key}\\,s & {len(values)} & "
            f"{statistics.median(values):.0f} & {percentile(values, 95):.0f} \\\\"
        )
    rows.append(r"\addlinespace")
    rows.append(r"\textit{Command-edge throughput (run\_index 1--29)} & & & \\")
    rows.append(
        f"  \\hspace{{2mm}}events/s & {len(tput)} & "
        f"{statistics.median(tput):.1f} & {percentile(tput, 95):.1f} \\\\"
    )

    with OUT.open("w", encoding="utf-8") as handle:
        handle.write("% Auto-generated by paper/scripts/generate_tables.py.\n")
        handle.write("% Do not edit; re-run the script after eval_metrics.jsonl changes.\n")
        for line in rows:
            handle.write(line + "\n")
        handle.write(r"\bottomrule" + "\n")
    print(f"wrote {OUT} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
