#!/usr/bin/env python3
"""Generate the Raft comparison table from evaluation JSONL."""

from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RAFT_DATA = ROOT / "data" / "eval_raft_baseline.anon.jsonl"
OUT = ROOT / "tables" / "tab_raft_comparison.tex"


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        sys.exit(f"ERROR: {path} missing")
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def percentile(values: list[float], p: float) -> float:
    xs = sorted(values)
    if not xs:
        raise ValueError("empty percentile")
    k = (len(xs) - 1) * (p / 100.0)
    f = int(k)
    c = min(f + 1, len(xs) - 1)
    if f == c:
        return xs[f]
    return xs[f] + (xs[c] - xs[f]) * (k - f)


def fmt_ms(value: float) -> str:
    if value >= 1000:
        return f"{value / 1000:.2f}\\,s"
    return f"{value:.1f}\\,ms"


def fmt_eps(value: float) -> str:
    return f"{value:.1f} events/s"


def main() -> None:
    raft = load_jsonl(RAFT_DATA)

    sanity = next(
        (
            record["scenario_params"]
            for record in raft
            if record.get("scenario") == "raft_sanity_event_seq_dedup"
            and record.get("metric_name") == "sanity_check"
        ),
        None,
    )
    if not sanity or not sanity.get("success"):
        sys.exit("ERROR: missing successful Raft event_seq/dedup sanity check")

    partition_runs = [
        record["scenario_params"]
        for record in raft
        if record.get("scenario") == "raft_leader_minority_partition"
        and record.get("metric_name") == "run"
    ]
    if not partition_runs:
        sys.exit("ERROR: missing raft_leader_minority_partition run records")

    elections = [
        params["time_to_new_leader_ms"]
        for params in partition_runs
        if params.get("time_to_new_leader_ms") is not None
    ]
    moved = sum(1 for params in partition_runs if params.get("l1_differs_from_l0"))
    committed = sum(1 for params in partition_runs if params.get("l1_writes_committed"))
    writes_per_run = partition_runs[0]["writes_per_run"]
    l0_behaviors = {
        behavior: sum(1 for params in partition_runs if params.get("l0_isolated_write_behavior") == behavior)
        for behavior in sorted({params.get("l0_isolated_write_behavior") for params in partition_runs})
    }
    l0_behavior_text = ", ".join(
        f"{behavior.replace('_', ' ')} {count}/{len(partition_runs)}"
        for behavior, count in l0_behaviors.items()
    )

    rows = [
        "Event sequencing sanity & "
        f"leader batch accepted {sanity['response']['accepted']} event, "
        f"deduplicated {sanity['response']['duplicates']}, "
        f"last seq. {sanity['response']['last_acked_seq']}; journal count {sanity['journal_count']} & "
        r"Confirms the Raft FSM assigns \textit{event\_seq} and enforces \textit{client\_event\_id} idempotency. \\",
        "Leader-minority partition & "
        f"{moved}/{len(partition_runs)} runs elected $L_1 \\ne L_0$; "
        f"{committed}/{len(partition_runs)} committed {writes_per_run} writes at $L_1$; "
        f"new-leader median {fmt_ms(statistics.median(elections))}, "
        f"p95 {fmt_ms(percentile(elections, 95))} & "
        f"$L_0$ writes while isolated: {l0_behavior_text}; authority follows the reachable quorum, not an external command designation. \\\\",

    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as handle:
        handle.write("% Auto-generated by scripts/generate_raft_table.py.\n")
        handle.write("% Do not edit; re-run the script after Raft evaluation JSONL changes.\n")
        for row in rows:
            handle.write(row + "\n")
        handle.write(r"\bottomrule" + "\n")
    print(f"wrote {OUT} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
