#!/usr/bin/env python3
"""Build paper/tables/tab_baseline.tex from Rescue OIS and Raft eval files."""

from __future__ import annotations

import json
import statistics
import sys
from pathlib import Path

OIS_DATA = Path("paper/data/eval_metrics.jsonl")
RAFT_DATA = Path("paper/data/eval_metrics_raft.jsonl")
OUT = Path("paper/tables/tab_baseline.tex")
OUT.parent.mkdir(exist_ok=True)


def load(path: Path) -> list[dict]:
    if not path.exists():
        sys.exit(f"missing {path}")
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle]


def median(values: list[float | None]) -> float:
    filtered = [value for value in values if value is not None]
    if not filtered:
        sys.exit("missing values for median")
    return statistics.median(filtered)


def percentile(values: list[float | None], p: float) -> float:
    filtered = sorted(value for value in values if value is not None)
    if not filtered:
        sys.exit("missing values for percentile")
    k = (len(filtered) - 1) * (p / 100)
    f = int(k)
    c = min(f + 1, len(filtered) - 1)
    if f == c:
        return filtered[f]
    return filtered[f] + (filtered[c] - filtered[f]) * (k - f)


def main() -> None:
    ois = load(OIS_DATA)
    raft = load(RAFT_DATA)

    ois_prop = [
        record["value_ms"]
        for record in ois
        if record["scenario"] == "field_edit_propagation"
        and record["scenario_params"].get("queue_depth") == 10
    ]
    raft_prop = [
        record["value_ms"]
        for record in raft
        if record["scenario"] == "baseline_raft_propagation"
        and record["scenario_params"].get("queue_depth") == 10
    ]
    ois_rec = [
        record["value_ms"]
        for record in ois
        if record["scenario"] == "wan_recovery"
        and record["scenario_params"].get("partition_s") == 60
    ]
    raft_rec = [
        record["value_ms"]
        for record in raft
        if record["scenario"] == "baseline_raft_follower_catch_up"
        and record["scenario_params"].get("partition_s") == 60
    ]
    quorum_results = [
        record["scenario_params"].get("write_succeeded")
        for record in raft
        if record["scenario"] == "baseline_raft_quorum_lost"
    ]

    rows = [
        r"\textit{Propagation, queue depth = 10} & & & \\",
        f"  Rescue OIS (this paper) & {len(ois_prop)} & {median(ois_prop):.1f} & {percentile(ois_prop, 95):.1f} \\\\",
        f"  Raft (3 voters) & {len(raft_prop)} & {median(raft_prop):.1f} & {percentile(raft_prop, 95):.1f} \\\\",
        r"\addlinespace",
        r"\textit{60\,s recovery (1 voter isolated)} & & & \\",
        f"  Rescue OIS (WAN to core) & {len(ois_rec)} & {median(ois_rec):.0f} & {percentile(ois_rec, 95):.0f} \\\\",
        f"  Raft (follower catch-up) & {len(raft_rec)} & {median(raft_rec):.0f} & {percentile(raft_rec, 95):.0f} \\\\",
    ]

    if quorum_results:
        succeeded = sum(1 for result in quorum_results if result)
        succeeded_pct = succeeded / len(quorum_results) * 100
        rows.extend(
            [
                r"\addlinespace",
                r"\textit{Quorum loss (2 of 3 isolated)} & & & \\",
                f"  Raft writes succeeded & {len(quorum_results)} & {succeeded_pct:.0f}\\% & --- \\\\",
            ]
        )

    with OUT.open("w", encoding="utf-8") as handle:
        handle.write("% Auto-generated by paper/scripts/generate_baseline_table.py.\n")
        handle.write("% Do not edit; re-run the script after eval data changes.\n")
        for row in rows:
            handle.write(row + "\n")
        handle.write(r"\bottomrule" + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
