#!/usr/bin/env python3
"""Plot fenced-promotion protocol-cost CDFs by phase.

Reads paper/data/eval_fenced_promotion.anon.jsonl, filters to per-attempt
records, splits by phase (A_pre / B_stale / C_post), and writes a
column-width CDF figure plus a TeX macro file with median, p95, and n.

The figure characterises the *protocol cost* of fenced promotion. The
end-to-end promotion wall-clock includes an operator-confirm step that
is not measured in this data; that scoping is stated in the prose
referencing this figure.
"""

from __future__ import annotations

import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

import matplotlib

matplotlib.rcParams["pdf.fonttype"] = 42
matplotlib.rcParams["ps.fonttype"] = 42
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "eval_fenced_promotion.anon.jsonl"
FIG_OUT = ROOT / "figures" / "fig_promotion_cost.pdf"
TEX_OUT = ROOT / "data" / "promotion_summary.tex"

PHASE_ORDER = ["A_pre", "B_stale", "C_post"]
PHASE_LABEL = {
    "A_pre": "Phase A: pre-transition commits",
    "B_stale": "Phase B: stale-epoch rejections",
    "C_post": "Phase C: post-transition commits",
}
PHASE_COLOR = {
    "A_pre": "#5b8db8",
    "B_stale": "#c47b2c",
    "C_post": "#4a7c4a",
}


def load_attempts():
    if not DATA.exists() or DATA.stat().st_size == 0:
        sys.exit(f"ERROR: {DATA} missing or empty.")
    with DATA.open(encoding="utf-8") as handle:
        records = [json.loads(line) for line in handle]
    return [r for r in records if r["metric_name"] == "attempt"]


def cdf_pairs(values):
    sorted_values = sorted(values)
    n = len(sorted_values)
    xs, ys = [], []
    for index, value in enumerate(sorted_values, start=1):
        xs.append(value)
        ys.append(index / n)
    return xs, ys


def percentile(values, p):
    sorted_values = sorted(values)
    n = len(sorted_values)
    if n == 0:
        return float("nan")
    idx = min(n - 1, int(p * n))
    return sorted_values[idx]


def main():
    attempts = load_attempts()
    by_phase = defaultdict(list)
    for record in attempts:
        phase = record["scenario_params"]["phase"]
        by_phase[phase].append(record["value_ms"])

    plt.rcParams.update({
        "font.size": 8,
        "axes.labelsize": 8,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "legend.fontsize": 7,
    })
    fig, ax = plt.subplots(figsize=(3.45, 2.4))

    all_values = []
    for phase in PHASE_ORDER:
        values = by_phase.get(phase, [])
        if not values:
            continue
        xs, ys = cdf_pairs(values)
        ax.plot(
            xs,
            ys,
            label=PHASE_LABEL[phase],
            color=PHASE_COLOR[phase],
            linewidth=1.4,
        )
        all_values.extend(values)

    overall_median = statistics.median(all_values)
    overall_p95 = percentile(all_values, 0.95)
    ax.axvline(overall_median, color="0.4", linewidth=0.6, linestyle="--")
    ax.axvline(overall_p95, color="0.4", linewidth=0.6, linestyle=":")
    # Vertical labels beside their lines at mid-height keep clear of the
    # lower-right legend and the climbing CDF curves.
    ax.text(
        overall_median, 0.55,
        f"median {overall_median:.1f} ms ",
        fontsize=7, color="0.3", rotation=90, ha="right", va="center",
    )
    ax.text(
        overall_p95, 0.55,
        f"p95 {overall_p95:.1f} ms ",
        fontsize=7, color="0.3", rotation=90, ha="right", va="center",
    )

    ax.set_xlabel("Per-attempt protocol latency (ms)")
    ax.set_ylabel("Cumulative fraction")
    ax.set_ylim(0.0, 1.0)
    upper_x = max(all_values) * 1.05
    ax.set_xlim(0, upper_x)
    ax.grid(axis="both", linestyle=":", linewidth=0.6, alpha=0.6)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.legend(loc="lower right", frameon=False)

    fig.tight_layout(pad=0.3)
    fig.savefig(FIG_OUT, bbox_inches="tight")
    plt.close(fig)

    n_total = len(all_values)
    n_per_phase = min(len(by_phase[p]) for p in PHASE_ORDER if p in by_phase)
    lines = ["% Auto-generated by scripts/plot_promotion_cdf.py."]
    lines.append(f"\\newcommand{{\\promotionN}}{{{n_total}}}")
    lines.append(f"\\newcommand{{\\promotionNPerPhase}}{{{n_per_phase}}}")
    lines.append(f"\\newcommand{{\\promotionMedianCombined}}{{{overall_median:.1f}\\,ms}}")
    lines.append(f"\\newcommand{{\\promotionPNinetyFiveCombined}}{{{overall_p95:.1f}\\,ms}}")
    phase_macro = {"A_pre": "A", "B_stale": "B", "C_post": "C"}
    for phase in PHASE_ORDER:
        values = by_phase.get(phase, [])
        if not values:
            continue
        med = statistics.median(values)
        p95 = percentile(values, 0.95)
        suffix = phase_macro[phase]
        lines.append(f"\\newcommand{{\\promotionMedian{suffix}}}{{{med:.1f}\\,ms}}")
        lines.append(f"\\newcommand{{\\promotionPNinetyFive{suffix}}}{{{p95:.1f}\\,ms}}")
    TEX_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"figure written to {FIG_OUT}")
    print(f"macros written to {TEX_OUT}")
    print(f"summary: n={n_total} (per phase {n_per_phase}) combined median={overall_median:.2f}ms p95={overall_p95:.2f}ms")
    for phase in PHASE_ORDER:
        values = by_phase.get(phase, [])
        if values:
            print(f"  {phase}: median={statistics.median(values):.2f}ms p95={percentile(values, 0.95):.2f}ms")


if __name__ == "__main__":
    main()
