#!/usr/bin/env python3
"""Generate the time-varying-connectivity and fleet-size tables from JSONL.

NET-02 (evaluate-netem-schedule.py) and NET-03 (evaluate-fleet-scaling.py) in
the artifact repository. Both tables are regenerated from the recorded runs;
do not edit the .tex files.
"""

from __future__ import annotations

import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEDULE_DATA = ROOT / "data" / "eval_netem_schedule.anon.jsonl"
FLEET_DATA = ROOT / "data" / "eval_fleet_scaling.anon.jsonl"
OUT_SCHEDULE = ROOT / "tables" / "tab_netem_schedule.tex"
OUT_FLEET = ROOT / "tables" / "tab_fleet_scaling.tex"

REGIME_LABEL = {
    "clear": "Clear",
    "mesh_stressed": "Mesh, stressed",
    "mesh_degraded": "Mesh, degraded",
    "isolated": "Isolated",
}


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        sys.exit(f"ERROR: {path} missing")
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def fmt_ms(value: float | None) -> str:
    if value is None:
        return "--"
    if value >= 1000:
        return f"{value / 1000:.2f}\\,s"
    return f"{value:.1f}\\,ms"


def write_schedule_table() -> None:
    records = load_jsonl(SCHEDULE_DATA)
    summaries = [r["scenario_params"] for r in records if r.get("metric_name") == "summary"]
    if not summaries:
        sys.exit("ERROR: no netem_schedule summary records")

    # Phase ordinal, not regime name: "clear" occurs twice in the schedule and
    # the second occurrence is the recovery phase, which means something else.
    by_phase: dict[int, dict] = defaultdict(lambda: {"ratios": [], "regime": None})
    for summary in summaries:
        for phase in summary.get("per_phase", []):
            entry = by_phase[phase["phase"]]
            entry["regime"] = phase["regime"]
            if phase.get("delivered_within_phase_ratio") is not None:
                entry["ratios"].append(phase["delivered_within_phase_ratio"])

    submitted = sum(s["submitted_total"] for s in summaries)
    journaled = sum(s["reached_journal_total"] for s in summaries)
    peaks = [s["peak_unforwarded"] for s in summaries]

    rows = []
    for ordinal in sorted(by_phase):
        entry = by_phase[ordinal]
        ratios = entry["ratios"]
        within = statistics.median(ratios) if ratios else None
        label = REGIME_LABEL.get(entry["regime"], entry["regime"])
        if ordinal and entry["regime"] == "clear":
            label += " (restored)"
        rows.append(
            f"{label} & "
            f"{'--' if within is None else f'{within:.2f}'} & "
            f"1.00 \\\\"
        )

    drains = [s["drain_time_s"] for s in summaries if s.get("drain_time_s") is not None]
    with OUT_SCHEDULE.open("w", encoding="utf-8") as handle:
        handle.write("% Auto-generated by scripts/generate_network_tables.py.\n")
        handle.write("% Do not edit; re-run the script after evaluation JSONL changes.\n")
        handle.write("\n".join(rows) + "\n")
        handle.write("\\bottomrule\n")
    print(
        f"wrote {OUT_SCHEDULE} ({len(rows)} rows; n={len(summaries)} runs, "
        f"{journaled}/{submitted} journaled, peak backlog {max(peaks)}, "
        f"recovery median {statistics.median(drains):.2f}s)"
    )


def write_fleet_table() -> None:
    records = load_jsonl(FLEET_DATA)
    summaries = [r["scenario_params"] for r in records if r.get("metric_name") == "size_summary"]
    if not summaries:
        sys.exit("ERROR: no fleet size_summary records")
    summaries.sort(key=lambda s: s["fleet_size"])

    runs = [r["scenario_params"] for r in records if r.get("metric_name") == "run"]
    events = sum(r["journaled"] for r in runs)
    expected = sum(r["expected_events"] for r in runs)

    rows = []
    for summary in summaries:
        rows.append(
            f"{summary['fleet_size']} & "
            f"{fmt_ms(summary['median_arrival_p50_ms'])} & "
            f"{fmt_ms(summary['median_arrival_p95_ms'])} & "
            f"{summary['median_journal_throughput_eps']:.1f} & "
            f"{summary['min_delivery_ratio']:.2f} \\\\"
        )
    with OUT_FLEET.open("w", encoding="utf-8") as handle:
        handle.write("% Auto-generated by scripts/generate_network_tables.py.\n")
        handle.write("% Do not edit; re-run the script after evaluation JSONL changes.\n")
        handle.write("\n".join(rows) + "\n")
        handle.write("\\bottomrule\n")
    print(f"wrote {OUT_FLEET} ({len(rows)} rows; {events}/{expected} events journaled)")


def main() -> int:
    write_schedule_table()
    write_fleet_table()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
