#!/usr/bin/env python3
"""Generate tables/tab_falsification_cost.tex from formal/tla/RUNS.md.

Extracts the strict large-run row (verification cost) and the three weak
variant rows (counterexample cost), and emits a TeX table body that
contrasts distinct states, wall-clock, and graph-search depth.

Strict and weak run tables in RUNS.md have different column layouts; the
script handles each explicitly.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RUNS_MD = ROOT / "formal" / "tla" / "RUNS.md"
TABLE_OUT = Path(__file__).resolve().parents[1] / "tables" / "tab_falsification_cost.tex"

STRICT_COLUMNS = [
    "config", "constants", "symmetry", "result",
    "generated", "distinct", "queue_left", "depth", "wall", "invariants",
]
WEAK_COLUMNS = [
    "config", "purpose", "violated", "trace_length", "depth",
    "generated", "distinct", "queue_left", "wall",
]


def split_row(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip("|").split("|")]


def parse_runs(md_text: str) -> tuple[dict[str, dict], dict[str, dict]]:
    strict: dict[str, dict] = {}
    weak: dict[str, dict] = {}
    section = None
    for line in md_text.splitlines():
        if line.startswith("## Strict"):
            section = "strict"; continue
        if line.startswith("## Weak"):
            section = "weak"; continue
        if not line.startswith("| `"):
            continue
        cells = split_row(line)
        name = cells[0].strip("`")
        if section == "strict":
            strict[name] = dict(zip(STRICT_COLUMNS, cells))
        elif section == "weak":
            weak[name] = dict(zip(WEAK_COLUMNS, cells))
    return strict, weak


def to_int(value: str) -> int:
    return int(value.replace(",", ""))


def to_seconds(value: str) -> float:
    match = re.match(r"([\d.]+)\s*s", value)
    if not match:
        raise ValueError(f"cannot parse wall-clock {value!r}")
    return float(match.group(1))


def format_states(states: int) -> str:
    if states >= 1_000_000:
        return f"{states / 1_000_000:.2f}\\,M"
    if states >= 1_000:
        return f"{states / 1_000:.1f}\\,k"
    return f"{states}"


def format_seconds(seconds: float) -> str:
    if seconds >= 60.0:
        return f"{seconds / 60.0:.1f}\\,min"
    return f"{seconds:.2f}\\,s"


def main():
    if not RUNS_MD.exists():
        sys.exit(f"ERROR: {RUNS_MD} missing.")
    strict, weak = parse_runs(RUNS_MD.read_text(encoding="utf-8"))

    if "RescueOIS_large.cfg" not in strict:
        sys.exit("ERROR: strict large row not found")
    for cfg in ("RescueOIS_weak.cfg", "RescueOIS_weak_epoch.cfg", "RescueOIS_weak_journal.cfg"):
        if cfg not in weak:
            sys.exit(f"ERROR: weak row {cfg} not found")

    strict_row = strict["RescueOIS_large.cfg"]
    rows: list[tuple[str, str, str, str]] = [(
        "strict",
        "all six invariants pass",
        format_states(to_int(strict_row["distinct"])),
        format_seconds(to_seconds(strict_row["wall"])),
    )]

    weak_labels = {
        "RescueOIS_weak.cfg": ("weak", "\\textit{SingleAuthority} violated"),
        "RescueOIS_weak_epoch.cfg": ("weak", "\\textit{EpochAuthorityCoupling} violated"),
        "RescueOIS_weak_journal.cfg": ("weak", "\\textit{NoForkedJournal} violated"),
    }
    for cfg, (variant, outcome) in weak_labels.items():
        row = weak[cfg]
        rows.append((
            variant,
            outcome,
            format_states(to_int(row["distinct"])),
            format_seconds(to_seconds(row["wall"])),
        ))

    lines = ["% Auto-generated by scripts/plot_falsification_cost.py."]
    for variant, outcome, states, wall in rows:
        lines.append(f"{variant} & {outcome} & {states} & {wall} \\\\")
    lines.append("\\bottomrule")
    TABLE_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"table written to {TABLE_OUT}")
    for line in lines:
        print(line)


if __name__ == "__main__":
    main()
